// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHdDfJV9fD_Q6oKCGOL6gmWmj1JQXhUwE',
    appId: '1:663219331575:web:ffdc71287685e495084ef2',
    messagingSenderId: '663219331575',
    projectId: 'userstorymapper-9f77f',
    authDomain: 'userstorymapper-9f77f.firebaseapp.com',
    storageBucket: 'userstorymapper-9f77f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwYyMIixAOUlccbV1Z-Ylgkm_g1-EJQAs',
    appId: '1:663219331575:android:e982f7e4eae5220a084ef2',
    messagingSenderId: '663219331575',
    projectId: 'userstorymapper-9f77f',
    storageBucket: 'userstorymapper-9f77f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn41oJkXdceXKygCuC0y6J5SeNulpRGCI',
    appId: '1:663219331575:ios:e63e437f7d21ed9c084ef2',
    messagingSenderId: '663219331575',
    projectId: 'userstorymapper-9f77f',
    storageBucket: 'userstorymapper-9f77f.appspot.com',
    iosBundleId: 'com.example.userStoryMapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn41oJkXdceXKygCuC0y6J5SeNulpRGCI',
    appId: '1:663219331575:ios:e63e437f7d21ed9c084ef2',
    messagingSenderId: '663219331575',
    projectId: 'userstorymapper-9f77f',
    storageBucket: 'userstorymapper-9f77f.appspot.com',
    iosBundleId: 'com.example.userStoryMapper',
  );
}
